import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AntdRegistry } from '@ant-design/nextjs-registry';

import NextAuthWrapper from "@/library/next.auth.wrapper";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "@Ka's Web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{margin: '0', padding: '0'}}>
        <Providers>
          <AntdRegistry>
            <NextAuthWrapper>
              {children}
            </NextAuthWrapper>
          </AntdRegistry>
  
        </Providers>
      </body>
    </html>
  );
}
